2019-05-28 22:00:48,004 - requests - ERROR - section is not in config
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\Python3-requests\Common\base.py", line 69, in config_read
    config_get = config.get(section, key)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'te1st'
2019-05-28 22:00:48,570 - requests - ERROR - section is not in config
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\Python3-requests\Common\base.py", line 69, in config_read
    config_get = config.get(section, key)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'te1st'
